version: '3.7'

services:
  web:
    build: 
        context: ./bestdockerappever
        dockerfile: paravoz.Dockerfile
    command: bash -c "sleep 3 && gunicorn analytics_project.wsgi -b 0.0.0.0:8001 --workers 2 --timeout 7200";
    networks:
      nginx_net:
    restart: always
    links:
      - db
    volumes:
      - ./bestdockerappever/:/usr/src/bestdockerappever/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    container_name: analytics_db_prod
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    networks:
      nginx_net:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      nginx_net:
    volumes:
      - ./application/media:/backend/src/media
      - ./application/static-backend:/backend/src/static-backend
      - ./frontend/build:/frontend/src
      - ./nginx/ssl:/etc/nginx/conf.d
      - ./nginx/ssl/data/certbot/conf:/etc/letsencrypt
      - ./nginx/ssl/data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped #+++
    networks:
      nginx_net:
    volumes:
      - ./nginx/ssl/data/certbot/conf:/etc/letsencrypt
      - ./nginx/ssl/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:


networks:
  nginx_net: